#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

import os 

name = 'para.foam' # name of temporary file 

# check if para.Foam exists 
if not(os.path.isfile(name)):

	os.system('touch ' + name)

# open with paraview 
os.system('paraview ' + name + ' &')