#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

import argparse 

parser = argparse.ArgumentParser(description='plot 2 column data') 
parser.add_argument('name', help='file name to open') 

args = parser.parse_args() 

f = open(args.name, 'r') 
var = [] 
x = [] 
y = [] 
for line in f:
	if (line.startswith('#')):
		var.append(line.strip('#').strip('\n')) 

		x.append([]) 
		y.append([]) 

	else:
		spl = line.split() 
		x[-1].append(float(spl[0])) 
		y[-1].append(float(spl[1])) 

f.close()

for i in range(len(x)):
	plt.plot(x[i], y[i], '-o', label=var[i]) 

plt.legend()
plt.show()

