#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

import sys 

if (len(sys.argv) != 2):
	print('provide a file name')
	sys.exit()

A = np.loadtxt(sys.argv[1])
plt.spy(A)
plt.show()