#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

import sys 

if (len(sys.argv)!=2):
	print('provide a file name')
	sys.exit() 

f = open(sys.argv[1]) 
height = 0
rows = 0 
for line in f: 
	if ('Number of My Rows' in line):
		height = int(line.split(' = ')[-1]) 
	if ('Number of My Cols' in line):
		width = int(line.split(' = ')[-1]) 

	if not('   Processor' in line):
		rows += 1
	else: 
		break 
rows += 1
p, row, col, val = np.loadtxt(sys.argv[1], skiprows=rows, unpack=True) 

print(p)
print(row)
print(col)
print(val) 

A = np.zeros((height, width))
for i in range(len(p)):
	A[int(row[i]), int(col[i])] = val[i] 

plt.spy(A)
plt.show()

